name: Deploy Jeju Movie Frontend

on:
  schedule:
    # 매일 자정 (UTC 기준)에 실행
    - cron: '0 0 * * *'
  workflow_dispatch: # 수동 실행을 위한 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # 프로젝트에 맞는 Node.js 버전으로 설정

    - name: Install root dependencies
      run: npm install

    - name: Install frontend dependencies and build
      run: npm run build
      working-directory: ./jejumovie-frontend

    - name: Deploy to Netlify
      # Netlify CLI를 사용하여 배포합니다.
      # Netlify CLI를 설치하고, NETLIFY_AUTH_TOKEN과 NETLIFY_SITE_ID를 GitHub Secrets에 추가해야 합니다.
      # 예시:
      # run: npm install netlify-cli -g && netlify deploy --prod --dir=./jejumovie-frontend/.next
      # env:
      #   NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #   NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: echo "Netlify deployment step goes here. Please configure NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID in GitHub Secrets."
